### PR TITLE
Enhanced UI of /update Page

### PR DESCRIPTION
**Pull request by zeddspear**
Hover effects are added on buttons of /update page and also made buttons more aligned.

### CODE REVIEW

**Comment by DevilsAutumn** [comment]
@zeddspear Can you please add before vs after screenshot associated with your changes?

**Comment by zeddspear** [comment]
> @zeddspear Can you please add before vs after screenshot associated with your changes?

Sure 

This is before :
Before

After:
After


I could add more details and effects to the buttons and form but there were no specific details were given that what type of changes they need.

**Review by DevilsAutumn — APPROVED** [review]

**Comment by DevilsAutumn** [comment]
@zeddspear Thankyou for this PR, the changes look really great but I will have to close this PR as the issue associated was assigned to someone else. Here are a few important tips I'd like to add:
1. Before you start working on any issue please get it assigned to you and then start working on it, it will be on first come first serve basis, for ex if 3 ppl have asked to work on a single issue , the issue will be assigned to the one who asked first . This same thing happens in many other open source projects.
2. If you think there is something which you can improve in the project, feel free to create an issue and mention that you are interested in working on that issue . If we assign that to you that means, the issue is valid and you can start working on it then.
3. Whenever you open a PR , always mention the issue it resolves.

Again , Thankyou for your efforts. Looking forward to see more PRs from you.

**Comment by zeddspear** [comment]
> @zeddspear Thankyou for this PR, the changes look really great but I will have to close this PR as the issue associated was assigned to someone else. Here are a few important tips I'd like to add:
> 
> 1. Before you start working on any issue please get it assigned to you and then start working on it, it will be on first come first serve basis, for ex if 3 ppl have asked to work on a single issue , the issue will be assigned to the one who asked first . This same thing happens in many other open source projects.
> 2. If you think there is something which you can improve in the project, feel free to create an issue and mention that you are interested in working on that issue . If we assign that to you that means, the issue is valid and you can start working on it then.
> 3. Whenever you open a PR , always mention the issue it resolves.
> 
> Again , Thankyou for your efforts. Looking forward to see more PRs from you.

Thanks for the tips 
I'll consider these in future.

**Pull request closed without merging**
