### PR TITLE
Enhance UI: Improve Buttons on /update Page : issue#24

### LINKED ISSUE #24: Enhance UI: Improve Buttons on /update Page
### Issue Description
The current UI of buttons on the `/update` page needs improvement for a better user experience. This issue is raised to discuss and implement enhancements to the button design.

### Areas for Improvement
- Provide details on specific buttons or aspects of the UI that need enhancement.
- Consider adding visual elements, such as icons or styling, to make buttons more intuitive.

### PR DESCRIPTION
**Pull request by devloves**
Fix #24

### CODE REVIEW

**Comment by devloves** [comment]
@krishnan05 Review Required

**Comment by krishnan05** [comment]
> @krishnan05 Review Required

Can you attach screenshots of original and changed part

**Comment by devloves** [comment]
**New**
image
**Old**
image
image

**Comment by devloves** [comment]
@krishnan05 here you go

**Review by DevilsAutumn — APPROVED** [review]

**Pull request merged**
